name: linkie
description: A simple command-line wrapper for the Linkie API
version: 0.1.2

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies: 
  args: ^2.3.1
  build_runner: ^2.1.11
  console: ^4.1.0
  http: ^0.13.4
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  logging: ^1.1.0
